name: llms
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - python-dotenv
  - requests
  - numpy
  - pandas
  - scipy
  - pytorch
  - ipywidgets
  - matplotlib
  - scikit-learn
  - chromadb
  - jupyter-dash
  - pyarrow
  - pip:
    - accelerate
    - agno
    - beautifulsoup4
    - bitsandbytes
    - plotly
    - pypdf
    - PyPDF2
    - transformers
    - sentence-transformers
    - streamlit
    - datasets==3.6.0
    - diffusers
    - openai
    - openai-agents
    - anthropic
    - google-generativeai
    - gradio
    - gensim
    - modal
    - ollama
    - psutil
    - setuptools
    - speedtest-cli
    - soundfile
    - langchain
    - langchain-core
    - langchain-text-splitters
    - langchain-openai
    - langchain-ollama
    - langchain-chroma
    - langchain-community
    - langchain-mcp-adapters
    - langgraph
    - langgraph-sdk
    - langgraph-prebuilt
    - langgraph-checkpoint-sqlite
    - langgraph-cli[inmem]
    - langsmith
    - lancedb
    - feedparser
    - fastapi
    - flask
    - twilio
    - pydub
    - protobuf==3.20.2
    - pinecone-client
    - trustcall
    - rich
    - wikipedia
    - sentencepiece
