[project]
name = "mcp-shell-server"
version = "0.1.0"
description = "FastMCP Terminal Server - Execute shell commands via MCP"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=0.2.0",
]
